language: android
android:
    components:
        - platform-tools
        - tools

        - build-tools-28.0.3

        - android-23
        
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

before_script:
        - chmod +x gradlew
        - touch local.properties
        - echo "storeFile=data" >> local.properties
        - echo "storePassword=123456789" >> local.properties

script: "./gradlew build"
